### PR TITLE
Bump firebase and migrating to Xcode 9

### LINKED ISSUE #20: Linker errors with Xcode 9
Here's a subset, but I got more than 200 errors:

```
"_nano_encode_repeated_string", referenced from:
      _firapb_set_string_filter_encoders in FirebaseAnalytics(firapb_string_filter_encoder_f42092f1ba2fa9d559b019faba84cc6a.o)
  "_nano_encode_repeated_uint64", referenced from:
      _firapb_set_result_data_encoders in FirebaseAnalytics(firapb_result_data_encoder_373a816d02f878f3857bb6d0ba8021a2.o)
  "_nano_encode_string", referenced from:
      _firapb_set_event_encoders in FirebaseAnalytics(firapb_event_encoder_0c153acc04fdbe51594c94848d0368b0.o)
      _firapb_set_event_config_encoders in FirebaseAnalytics(firapb_event_config_encoder_b76c27c645bff35f43c88abf3308a055.o)
      _firapb_set_event_filter_encoders in FirebaseAnalytics(firapb_event_filter_encoder_622d09830d24d1c5bf26be1b23f22eb3.o)
      _firapb_set_event_param_encoders in FirebaseAnalytics(firapb_event_param_encoder_fb98584a84d6fa363809bc8f957886cc.o)
      _firapb_set_filter_encoders in FirebaseAnalytics(firapb_filter_encoder_d28bfc4dffa3c4e05d93004539cd7c73.o)
      _firapb_set_measurement_bundle_encoders in FirebaseAnalytics(firapb_measurement_bundle_encoder_e7a36a02602e2fe11129d880f043b544.o)
      _firapb_set_measurement_config_encoders in FirebaseAnalytics(firapb_measurement_config_encoder_3181c28b3408a1f4c47b43a54bb352cc.o)
      ...
```

Anyone else getting that? Any workaround?

### PR DESCRIPTION
**Pull request by tbaranes**
While looking how to fix #20, I bumped Firebase to the latest version and migrating the current code to Xcode 9. Opening this PR even if there's still linking errors, not sure how to fix them.

### CODE REVIEW

**Comment by soheilbm** [comment]
@tbaranes could you update readme file to correspond with updated libraries

**Comment by cyoungberg** [comment]
I resolved the linking errors by adding -lz and -lsqlite3 as "Other Linker Options"  (along with `-ObjC` as indicated by the readme)

**Comment by tbaranes** [comment]
@soheilbm Sorry for the delay, I didn't see your answer. I updated again the frameworks, and the README is up to date.
@cyoungberg Tried this in the example of this repository, didn't work, will try later in my own project

**Comment by tbaranes** [comment]
@soheilbm I also noticed their is `Firestore` available as well but didn't include it, I think it deserves another PR.

**Comment by soheilbm** [comment]
@tbaranes thanks for updating 👍 
I merge this for now

**Pull request merged**
